on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: bzlmodrio/vendor-json-repo/.github/actions/add_vendordep@c8b5ff6a67c481c9ee790b7457c5a2f166603ff3
        with:
          token: ${{ secrets.VENDOR_DEPLOY }}
          vendordep_file: ../rev.json
          pr_title: "DO NOT LAND - testing auto-publish action"
          pr_branch: "testing_update_v99"
          is_beta: true
          fork_organization: bzlmodrio
